### ISSUE TITLE
Viewing the rose on the vase in Pronterface

### ISSUE THREAD

**Issue by markingle** [MarkWheadon/velocity-painting#11]
Hello Mark!  This is awesome!  I am eager to try this code from Slic3r but I need to get familiar with what you have done.  In viewing the vase with a rose in Pronterface I don't see the image...the before and after gcode are the same.  Can you confirm the rose image is present?

Also I have a background in C++, php...its been awhile since I have worked with Perl but I think figure things out.

**Comment by MarkWheadon** [comment]
Does Pronterface show print speed in some way? If it doesn't then that would explain why you're not seeing the pattern -- it only exists as a change in velocity, there's no change in the shape described by the GODE at all.

**Comment by markingle** [comment]
Nevermind....looks like Pronterface does not color code speed!

**Comment by MarkWheadon** [comment]
Yes, it's a bit of a problem that, so far as I know, only Simplify3D does a decent job of showing the changes in speed.

**Comment by markingle** [comment]
CraftWare reads the code but errors are generated.  However the rendering implies there is some consistency in the errors which may mean the effort to correct maybe simple

CraftWare shows color of speed but its in mm/s

<img width="603" alt="screen shot 2017-03-22 at 7 26 21 pm" src="https://cloud.githubusercontent.com/assets/11239466/24225187/9074ceea-0f35-11e7-9cf1-08a5a36d2c92.png">


<img width="1054" alt="screen shot 2017-03-22 at 6 42 03 pm" src="https://cloud.githubusercontent.com/assets/11239466/24224048/7c31459a-0f2f-11e7-9878-1cc083a40fc5.png">
