### ISSUE TITLE
Trouble with ImageMagick

### ISSUE THREAD

**Issue by markingle** [MarkWheadon/velocity-painting#12]
I am struggling to get past the loading of ImageMagick on my Mac running Sierra 10.12.3 when running velPaint.

I have change the perl location in velPaint from/to

#!/opt/local/bin/perl -w
#!/usr/bin/perl -w

I get the following error msg:

Can't locate Image/Magick.pm in @INC (you may need to install the Image::Magick module) (@INC contains: /Users/Mark/perl5/lib/perl5/5.18.2/darwin-thread-multi-2level /Users/Mark/perl5/lib/perl5/5.18.2 /Users/Mark/perl5/lib/perl5/darwin-thread-multi-2level /Users/Mark/perl5/lib/perl5 /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2/darwin-thread-multi-2level /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at ./velPaint line 13.

I suspect the issue has to do with locating the magick perl install...magick is installed!

MACITG111080L:~ Mark$ magick -version
Version: ImageMagick 7.0.5-3 Q16 x86_64 2017-03-18 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules 
Delegates (built-in): bzlib freetype jng jpeg ltdl lzma png tiff xml zlib

Any ideas on troubleshooting this?

**Comment by vef445** [comment]
ImageMagick can be challenging... Have you installed perlmagick after imagemagick?

**Comment by markingle** [comment]
Yes PerlMagick is installed but I still get the same error...I can successfully display the logo as a test too
<img width="844" alt="screen shot 2017-03-23 at 7 05 48 pm" src="https://cloud.githubusercontent.com/assets/11239466/24273971/d8b33ab8-0ffb-11e7-8a21-307977ff01bd.png">

**Comment by vef445** [comment]
What is the result when you do 'perl Makefile.PL' ?

**Comment by vef445** [comment]
Displaying the logo is related to ImageMagick, not directly to PerlMagick if I'm not wrong... :/

**Comment by markingle** [comment]
MACITG111080L:velocity-painting-master Mark$ perl Makefile.PL
Checking if your kit is complete...
Looks good
Warning: prerequisite Image::Magick 0 not found.
Generating a Unix-style Makefile
Writing Makefile for Velocity::Painting
Writing MYMETA.yml and MYMETA.json
MACITG111080L:velocity-painting-master Mark$

**Comment by markingle** [comment]
I installed ImageMagick with Brew originally.  After vef455 comment about PerlMagick I did a reinstall of ImageMagick with "brew reinstall imagemagick --with-perl"

Now error message is different than the original above....

Can't locate Image/Magick.pm in @INC (you may need to install the Image::Magick module) (@INC contains: /opt/local/lib/perl5/site_perl/5.24/darwin-thread-multi-2level /opt/local/lib/perl5/site_perl/5.24 /opt/local/lib/perl5/vendor_perl/5.24/darwin-thread-multi-2level /opt/local/lib/perl5/vendor_perl/5.24 /opt/local/lib/perl5/5.24/darwin-thread-multi-2level /opt/local/lib/perl5/5.24 .) at ./velPaint line 13.
BEGIN failed--compilation aborted at ./velPaint line 13.

**Comment by markingle** [comment]
Made a little progress running ./configure --with-perl

<img width="830" alt="screen shot 2017-03-23 at 9 44 12 pm" src="https://cloud.githubusercontent.com/assets/11239466/24277198/f7501b6a-1011-11e7-88de-6fc0be779c60.png">

**Comment by markingle** [comment]
I had to add the following to velPaint

use lib "/Users/Mark/ImageMagick-7.0.5-3/PerlMagic/default";

This is where the Magick.pm file is located.  Also I had to install ImageMagick and compile with make...for some reason the brew install would not work placing "use lib...." in velPaint.

The command now responds with syntax info on the parameters....finally get to start playing!!!
