### ISSUE TITLE
ProjectX and CylinderZ

### ISSUE THREAD

**Issue by markingle** [MarkWheadon/velocity-painting#13]
What is the difference between these two parameters?

**Comment by MarkWheadon** [comment]
projectX projects the image onto the X axis (as if the X axis were a
projector screen) -- so the image runs through the model like words through
a stick of Blackpool rock.

cylinderZ wraps the image round an upright cylinder, so it appears as if it
has been wrapped around the model (so great for vases for example).

Does that help?

**Comment by markingle** [comment]
Yes it does!  Thanks Mark!  I designed a "vase" for my wife and I would like to put hearts in a checkers board pattern on the outside using velPaint.  It sounds like I should use projectX?

I took the day off work to get this going...lol

<img width="977" alt="screen shot 2017-03-24 at 2 22 50 pm" src="https://cloud.githubusercontent.com/assets/11239466/24308275/c19ffc2e-109d-11e7-9c92-f7ebb7831841.png">

**Comment by markingle** [comment]
Not quite checkered but progress none the less! (see middle bottom)

Here is the command I used:

./velPaint -projectX 0 0 22 20 0 3000 1800 3000 /Users/Mark/Downloads/Heart.png /Users/Mark/Downloads/MyHeart.gcode > MyHeart_VP.gcode

How do I config for a checkered pattern?

<img width="804" alt="screen shot 2017-03-24 at 3 17 03 pm" src="https://cloud.githubusercontent.com/assets/11239466/24310131/0f2e8378-10a5-11e7-953c-0b4d5311979d.png">

**Comment by markingle** [comment]
I figured it out!  After thinking about it a little more its as simple a choosing a png file with the pattern that you want.  Using the projectX switch "projects" the checkered pattern image on to/through the object!

Excellent work Mark W.!

<img width="871" alt="screen shot 2017-03-24 at 4 03 56 pm" src="https://cloud.githubusercontent.com/assets/11239466/24311746/d28de204-10ab-11e7-8808-10bb5a2a590c.png">

**Comment by MarkWheadon** [comment]
Looks great.

Mark
