### ISSUE TITLE
Extrusion issue

### ISSUE THREAD

**Issue by markingle** [MarkWheadon/velocity-painting#14]
Are there any speed requirements for the extrusion rate when using VelPaint?  My first test print had poor extrusion on the faster speed sections.  I am using Slic3r at the moment to create the gcode.  I do plan on using Simplified 3D at some point but want to get more information before troubleshooting

**Comment by MarkWheadon** [comment]
I find 2400mm/min is good, 3600mm/min starts to produce holes. That's with
a low speed of 800mm/min. I suspect it's more about the difference between
the two speeds than it is about the absolute speeds.

What sort of speeds are you using?

Mark

**Comment by markingle** [comment]
I used the following:

./velPaint -projectX 0 0 200 200 0 3000 1800 3000 /Users/Mark/Downloads/HeartPattern.png /Users/Mark/Downloads/MyHeart.gcode > MyHeart_VP.gcode

I will try something that reduces the difference between print and extrusion speeds

**Comment by MarkWheadon** [comment]
Try

./velPaint -projectX 0 0 200 200 0 3000 800 2400
/Users/Mark/Downloads/HeartPattern.png
/Users/Mark/Downloads/MyHeart.gcode > MyHeart_VP.gcode

and run your PLA hot -- say 230C?

**Comment by markingle** [comment]
Good heavens!  My filament diameter was set to 3mm and I am using 1.75mm!  How embarrassing! 

Sorry to bother you Mark!

**Comment by MarkWheadon** [comment]
No worries,

Mark

**Comment by markingle** [comment]
Very nice work Mark!  First test run was a success!

![unnamed-2](https://cloud.githubusercontent.com/assets/11239466/24502821/6e2928ca-151d-11e7-9b3e-f72bae955246.jpg)

**Comment by MarkWheadon** [comment]
Nice one! 👍

**Comment by MarkWheadon** [comment]
What's the filament? It works well.

**Comment by markingle** [comment]
Hatchbox transparent Green @ 220C.  I calibrate my filament using this method:

https://docs.google.com/spreadsheets/d/1tXXoEXopqVC0rSecXhBakv75ahq7rz5tL0GSG6RqEBM/edit#gid=1788374336
