### ISSUE TITLE
zOffset portion defaults to extremely slow speed

### ISSUE THREAD

**Issue by markingle** [MarkWheadon/velocity-painting#15]
I got some time to test the new version of velPaint while traveling and found an issue with the zOffset section generated at a very slow speed @ 600/mm.  My testing was done with the Cylinder Print Type.....seems like it should be set to the lowSpeed value?

<img width="591" alt="screen shot 2017-04-02 at 12 14 27 pm" src="https://cloud.githubusercontent.com/assets/11239466/24588860/8de959ae-179e-11e7-9a93-f6919f20f12c.png">

<img width="1109" alt="screen shot 2017-04-02 at 12 14 12 pm" src="https://cloud.githubusercontent.com/assets/11239466/24588930/925dbc68-179f-11e7-993e-8b44676a2d31.png">

The interface is a great addition!  Great work Guillaume!

.

**Comment by MarkWheadon** [comment]
That does look odd. It also looks like there are holes in that bottom section (on the right for example)? Could you attach the files you used to create the above scenario?

**Comment by MarkWheadon** [comment]
FYI I don't know if Guillaume is listening here. Are you listening Guillaume? :)

**Comment by markingle** [comment]
The holes are part of the design!  There is a tiny drawer for the new ring!  :)

files are attached....rename from .txt to .gcode
[MainHeart.txt](https://github.com/MarkWheadon/velocity-painting/files/890734/MainHeart.txt)

![heartpattern](https://cloud.githubusercontent.com/assets/11239466/24620311/2a4a0240-186b-11e7-8f77-fa7b48e7b383.png)

**Comment by vef445** [comment]
Yes I'm here :)
As I replied on the other bug reported by @markingle , I'm not sure UI-related issues should pollute this Git, but I'll pass by regularly anyway.

For this specific issue, I will test and compare if the result is the same while the UI or command line and report on my finding.

**Comment by vef445** [comment]
@MarkWheadon , you should look at your code, I've got the exact same result when using my UI or launching the process directly in command line. (I was concerned by the extra space generated by the UI when "image width" is not used/set).
![screen shot 2017-04-04 at 11 43 49](https://cloud.githubusercontent.com/assets/5900426/24651096/c45081f4-192c-11e7-88e9-44a8a79567b1.png)
![screen shot 2017-04-04 at 11 47 31](https://cloud.githubusercontent.com/assets/5900426/24651097/c489a0c4-192c-11e7-8bc6-e551023a80f6.png)

**Comment by MarkWheadon** [comment]
@markingle As an aside, you'll get better contrast if you modify that image to be pure black and white -- the red will be mapping onto a darkish grey rather than black, which means the hearts won't be mapping on to the high speed you specified.

**Comment by markingle** [comment]
Thanks @MarkWheadon !

**Comment by MarkWheadon** [comment]
I suspected as much. Will do.

**Comment by MarkWheadon** [comment]
It's becuase you have the high and low values the wrong way round -- you need to swap them. That, and making the heart pattern pure black-and-white gets you this:
<img width="741" alt="screenshot 2017-04-06 13 53 46" src="https://cloud.githubusercontent.com/assets/25584465/24755068/b7bd5f66-1ad0-11e7-8f0b-4ab19b995e8d.png">
Black and white pattern is this:
![heartsmonochrome](https://cloud.githubusercontent.com/assets/25584465/24755090/cc641de2-1ad0-11e7-9d93-aba15ce4ae69.png)

There's still a little fuzz on some of the top edge if you look closely. I'm guessing that's something that's not at a constant speed -- you still have one of the slow-downs configured in your S3D settings somewhere?

**Comment by MarkWheadon** [comment]
Or, on reflection, it could be a bug to do with it not noticing the first vector of a layer under some circumstances.
If there's nothing wrong with your slicer settings let me know and we may need to raise a separate issue.

**Comment by markingle** [comment]
@MarkWheadon Thanks for looking into this!  I am using slic3r to generate the gcode and S3D to view/confirm the changes (Also learning S3D to switch from Slic3r at the same time).  The high/low values were swapped to reduce the print time - 8hr to 5hr.  Now that I know how the contrast relates to speed there is no need to swap.  Thanks for creating a black/white for me.  I plan on making another print this weekend and will post here.  Really good work you have done!  I hope you make a $1M dollars!  :)

Is it possible the fuzz on top is from my retract settings in Slic3r?  Just a thought...

**Comment by MarkWheadon** [comment]
Heh, so do I, but the Bucket Of Money fairy appears to be busy elsewhere.

Mark
