### ISSUE TITLE
Destination Folder Issue

### ISSUE THREAD

**Issue by markingle** [MarkWheadon/velocity-painting#16]
When changing the destination folder a second time the new location is appended to the first location.  The string variable probably needs to be cleared when a click event occurs on the button....

<img width="729" alt="screen shot 2017-04-03 at 12 52 15 pm" src="https://cloud.githubusercontent.com/assets/11239466/24620817/2099f212-186d-11e7-964f-03d07cb9be7e.png">

**Comment by vef445** [comment]
Hi Markingle,
Thanks for reporting this bug.
This is specific to the VelocityPainting app/UI, not to Mark's code and what you'll find on this Git. To report bugs, you should (for now) use the form (contact page) on the dedicated website http://velocitypainting.webutu.com 

This won't be necessary for this bug as I have already fixed it in the next release :)

Mark (Wheadon), you can close this item.

**Comment by MarkWheadon** [comment]
Right you are.

**Comment by markingle** [comment]
@vef445 Thanks for the info.  I was not sure where to report the bug.  Nice work!  I was not able to get the new command line version to work so the UI is a big help!
