### ISSUE TITLE
Feature-Request: option to choose custom names to the painted file

### ISSUE THREAD

**Issue by ghost** [MarkWheadon/velocity-painting#17]
It would be a great feature if one could choose a custom name for his paintings. Everytime I process a file the old one gets overwritten by the new one due to the "painted.gcode".

**Comment by vef445** [comment]
This is solved in v0.5, please download the latest version (v0.5.1 today) ;)

@MarkWheadon , you can close.

**Comment by MarkWheadon** [comment]
👍
