### ISSUE TITLE
Start velPaint processing at zOffset

### ISSUE THREAD

**Issue by markingle** [MarkWheadon/velocity-painting#18]
@MarkWheadon I don't know if its possible but I think it would be best if the processing of the gcode to change speeds should start at the zOffset height as well.  This is the start of the location where the image will be projected so there is no need to adjust the speeds below the zOffset value.

In my use case I have a bottom section (up to 22mm) that will hold a battery, LEDs, and a drawer.  There is no need for the image to be projected into this portion so I have the image starting at 22mm.

<img width="878" alt="screen shot 2017-04-07 at 9 28 50 pm" src="https://cloud.githubusercontent.com/assets/11239466/24824490/065b1bf4-1bda-11e7-9284-c6c255cebeb5.png">

Hope this makes sense...not sure if its worth your time but thought I would mention it.  Let me know if this is "user error"

**Comment by MarkWheadon** [comment]
The problem I can see with that is that if the bottom portion is printed at
a different speed it will have a different surface texture or opacity so
there will be a slight difference between the un patterned​ and the
patterned areas.

Mark

**Comment by markingle** [comment]
This is true....In my use case I don't care about the difference in appearance on the bottom portion.  In an artistic use case this would would be a problem.
