### ISSUE TITLE
Cylinder not working in 0.5

### ISSUE THREAD

**Issue by preussja** [MarkWheadon/velocity-painting#19]
I have tested all the projections and I can't get cylinder to work. I'm getting this error in the terminal window "Argument "" isn't numeric in numeric eq (==) at script/VelocityPainting.pl line 772, <__ANONIO__> line 4."

**Comment by MarkWheadon** [comment]
Thanks I'll look into that. I expect it's the application frontend
providing an empty argument rather than no argument at all but I could be
wrong.

Mark

**Comment by vef445** [comment]
@preussja could you please send me the files (gcode and image) by email? vef445@gmail.com

[EDIT] Not needed, I've found the issue and it will be fixed in v0.5.1. I'll update the website asap, and let you know here when it's available.

**Comment by vef445** [comment]
Fixed in 0.5.1 (UI, not Mark's code).

@MarkWheadon , you can close.

**Comment by MarkWheadon** [comment]
Fabulous.
