### ISSUE TITLE
Script testing on ubuntu - image information

### ISSUE THREAD

**Issue by ghost** [MarkWheadon/velocity-painting#2]
I am currently testing the script on an ubuntu machine. it would be very helpful, if you could add specific information on the usage of images (size relative to the model, colors, dpi etc.).

**Comment by MarkWheadon** [comment]
Sure. There are a couple of constants in surfaceSpeed() -- xWidth and yWidth. They control the physical size of the image as it is projected through the model. So if xWidth and yWidth are, say, 20 then the image will be a 20mm square.

The image itself is mapped into greyscale by the script, so it can be colour or black and white or greyscale, and pretty much any image format, although it doesn't handle transparency right so if you have, say, a PNG file with transparency you need to map that transparency to (usually) white -- saving it as a JPEG is an effective way of doing that. 

I find black and white, simple images tend to look best, but greys between black and white will be handled correctly (with a speed part way between the lowest and the highest speeds).

DPI -- the more the merrier, but I would think 100 DPI once projected onto the model would be anough (so 80 pixels across for my 20mm example, for example). Having a low DPI may look great in some circumstances, as you'll be able to see the pixels (think Pacman, low-poly Pokemon etc., which benefit from the lo-tech look).

**Comment by ghost** [comment]
Great, thank you. I will test this out on cura 15.04.6 on, as I said, an ubuntu machine. I will also try on my main archlinux machine. i will give you some feedback when I have results.

**Comment by MarkWheadon** [comment]
Cool.

**Comment by MarkWheadon** [comment]
This was a good question so I've started an FAQ with it: https://github.com/MarkWheadon/velocity-painting/wiki/FAQ

**Comment by ghost** [comment]
Great! Thx.
