### ISSUE TITLE
Issue in Cylinder mode with specific gcode

### ISSUE THREAD

**Issue by vef445** [MarkWheadon/velocity-painting#20]
Hi @MarkWheadon ,
Someone sent me his gcode and it seems impossible to digest it, see attached file. The slicer is Cura, delta printer (Kossel plus), Marlin firmware.
[jarron spiral grande.gcode.txt](https://github.com/MarkWheadon/velocity-painting/files/908365/jarron.spiral.grande.gcode.txt)

**Comment by vef445** [comment]
Update: The same person actually succeed treating this file (he was a victim of the cylinder bug). Still I can't deal with his file, I think it's worth looking at it.

**Comment by MarkWheadon** [comment]
In what way can you not deal with it?
Mark

**Comment by MarkWheadon** [comment]
I can't see anything strange with the GCODE?

**Comment by vef445** [comment]
Sorry I didn’t get back to you on that one… please leave it open, I’ll look at it again tomorrow.

By the way, I received the following bug report about some sort of “welding” mark in cylinder mode, I’ll open a new issue on Github tomorrow.

**Comment by MarkWheadon** [comment]
Right you are.

Mark

**Comment by vef445** [comment]
Issue was on my side, you can close @MarkWheadon
