### ISSUE TITLE
struggle with finding all the dependencies

### ISSUE THREAD

**Issue by dp90pusika** [MarkWheadon/velocity-painting#3]
Hy Mark, this is an amazing script you wrote.
I would love to experiment with it on some prints, but I'm really struggling with setting up the program.

My problem is probably related to imagemagick, I can't find the right dependencies. Can you point me in the right direction, where can I fond the right modules to run your program?
The error message I get is:

> Exception 495: RegistryKeyLookupFailed 'CoderModulesPath' @ error/module.GetMagickModulePath/664 at C:\velpaint\velPaint.pl line 30.

**Comment by MarkWheadon** [comment]
Hi -- what operating system are you using?

**Comment by dp90pusika** [comment]
I'm on windows. 
I went down a rabbit hole with it, image magick pack asked to be installed trough visual studio, visual studio complained that it needs the 2010 compiler to build the magick installer.
Tried several compiled packages, they install but the cmd and perl consoles don't find the dll that are installed

**Comment by MarkWheadon** [comment]
If I have any bright ideas I'll let you know, but I don't at the moment -- perhaps someone else reading this will have more specific knowledge?

**Comment by dp90pusika** [comment]
okay, I will struggle a bit more with it, maybe I find the solution. Hope this gets implemented in a more usable form, it's a great idea that uses a hidden capability of printers

**Comment by beanz** [comment]
The requirements of the script are quite simple but Image::Magick is quite complex. Perhaps a simpler to build dependency could be used? @dp90pusika can you try installing the Imager module instead? Let me know if it works. If it does, I'll happily create a pull request to use that instead.

**Comment by dp90pusika** [comment]
Hy @beanz,
I abandoned the windows version, 
Instead I installed a virtual ubuntu, and there it was much easier to identify the missing packages.
So now I can use the script with no problem:
https://www.facebook.com/3dprintedlife/posts/1839751912939191

I'm quite novice at programming so I can't really help out in the development of this program.
But I find it a really useful tool and I hope It will get a more user friendly shel so anybody can access it.

**Comment by MarkWheadon** [comment]
It certainly doesn't use much of Image::Magick. Just mapping to greyscale,
fetching width and height of image and fetching pixel values.

**Comment by dp90pusika** [comment]
I'll give it a try but I'm pretty sure it's already installed.
The error messages say that the need dll-s can't be found, but I can clearly se them in the right folders.

But again, I really don't have any idea what I'm doing, so many I missed something

**Comment by ghost** [comment]
You could try, if you are on Windows 10, to activate the Linux subsystem. I haven't tried this but you should be able to install imagemagick, Perl and perlmagick from there and execute the script. Unfortunately the Perl plugs for Windows 10 don't work (as far as I have tried).

Cheers

**Comment by MarkWheadon** [comment]
Good news on this: Guillaume Vigneron has submitted changes to me that remove the dependency on Imagemagick and instead use the simpler Imager. I should be pushing the change, merged with some additions of my own, later today.

**Comment by MarkWheadon** [comment]
OK the new version (just uploaded) should be much less of a pain?
