### ISSUE TITLE
No changes in GCode after script

### ISSUE THREAD

**Issue by revpolitic** [MarkWheadon/velocity-painting#4]
I try your script but no changes in Gcode preview. 
I install Perl and Image::Magick module for Perl and follow instructions but GCode before and after seems to be identical.
I try waterVase21 model from Thingiverse, sliced in S3D with all speeds to 30mm/s so 1800mm/min and some images resized to different values and formats (only .bmp works for me) but i can't make script working correctly in my computer. 
From terminal i type:
perl velPaint 1800 1800 3000 image.bmp Before.gcode > After.gcode

Can u upload a model and image i can test with?

**Comment by MarkWheadon** [comment]
Ok I have a couple of ideas for you to try (based on my experience of processing other people's GCODE).

Chances are either (1) the regular expressions aren't matching the lines, or (2) the pattern is outside of the model:

(1) GCODE produced in the Windows environment has literal newlines (control-M) at the end of the line, so after

        chomp $line;

add

        $line =~ s/\r//g;

And the other issue (2) may be the coordinate system. My printer is a delta, so (0,0) is in the middle of the bed. Some more conventional printers have (0,0) in the middle like my delta (Replicator 2 seems to be one of those), but some have it front-left -- so the middle of the Prusa i3 MK2 is at (125,125).

If you slice something small at the middle of the bed and then look at the GCODE in a text editor you will be able to see what the coordinate system is.

If your origin is at, say, 125,125 then you need to subtract 125 from the x and y parameters in surfaceSpeed. So something like:

my $xNormalized = ($x - 125 + $yWidth / 2) / $yWidth;

Do either of these fixes apply to you?

**Comment by revpolitic** [comment]
Thanks Mark, I just try to slice in S3d Linux with the object at 0,0 and **it's work**. I can see changes in Gcode.
First i'm going to choose a image to work with and after everything works fine i'll try to modify the Script to work with my printer. 

Thanks.

**Comment by MarkWheadon** [comment]
Great stuff.
