### ISSUE TITLE
Generated but not print

### ISSUE THREAD

**Issue by jpramez** [MarkWheadon/velocity-painting#7]
I generated GCODE and opened it in repetier fine but not in Simplify3D, and when i try to print i cannot do it

**Comment by MarkWheadon** [comment]
Perhaps you could generate a very small example and attach the original
gcode and the processed gcode?

Cheers,

Mark

**Comment by jpramez** [comment]
any mail to send it? i cannot upload it here.

Which versión of perl you used?

**Comment by ghost** [comment]
just send it to tausendkubik@gmail.com. i will try.
